name: CI/CD Pipeline

on:
  push:
    branches:
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Terraform Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push app image
        run: |
          docker build -t myapp ./app
          docker tag myapp:latest ${{ secrets.ECR_APP_URL }}:latest
          docker push ${{ secrets.ECR_APP_URL }}:latest

      - name: Build, tag, and push nginx image
        run: |
          docker build -t nginx ./nginx
          docker tag nginx:latest ${{ secrets.ECR_NGINX_URL }}:latest
          docker push ${{ secrets.ECR_NGINX_URL }}:latest